# Generated by Django 4.0 on 2021-12-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
